/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 06 15:30:03 GMT 2016
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Percolation_ESTest extends Percolation_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 167 covered goals:
   * Goal 1. Percolation.isOpen(II)Z: root-Branch
   * Goal 2. Percolation.<init>(I)V: I7 Branch 1 IFLE L22 - false
   * Goal 3. Percolation.<init>(I)V: I10 Branch 2 IF_ICMPLT L22 - true
   * Goal 4. Percolation.index(II)I: I3 Branch 14 IFLE L94 - false
   * Goal 5. Percolation.index(II)I: I7 Branch 15 IF_ICMPGT L94 - false
   * Goal 6. Percolation.index(II)I: I9 Branch 16 IFLE L94 - false
   * Goal 7. Percolation.index(II)I: I13 Branch 17 IF_ICMPLE L94 - true
   * Goal 8. Branch Percolation.isOpen(II)Z: root-Branch in context: Percolation:isOpen(II)Z
   * Goal 9. Branch Percolation.<init>(I)V: I10 Branch 2 IF_ICMPLT L22 - true in context: Percolation:<init>(I)V
   * Goal 10. Branch Percolation.<init>(I)V: I7 Branch 1 IFLE L22 - false in context: Percolation:<init>(I)V
   * Goal 11. Branch Percolation.index(II)I: I9 Branch 16 IFLE L94 - false in context: 
   * Goal 12. Branch Percolation.index(II)I: I3 Branch 14 IFLE L94 - false in context: 
   * Goal 13. Branch Percolation.index(II)I: I7 Branch 15 IF_ICMPGT L94 - false in context: 
   * Goal 14. Branch Percolation.index(II)I: I13 Branch 17 IF_ICMPLE L94 - true in context: 
   * Goal 15. Percolation.<init>(I)V: Line 22
   * Goal 16. Percolation.<init>(I)V: Line 25
   * Goal 17. Percolation.<init>(I)V: Line 26
   * Goal 18. Percolation.<init>(I)V: Line 28
   * Goal 19. Percolation.<init>(I)V: Line 29
   * Goal 20. Percolation.<init>(I)V: Line 30
   * Goal 21. Percolation.<init>(I)V: Line 31
   * Goal 22. Percolation.<init>(I)V: Line 32
   * Goal 23. Percolation.index(II)I: Line 94
   * Goal 24. Percolation.index(II)I: Line 97
   * Goal 25. Percolation.isOpen(II)Z: Line 79
   * Goal 26. Percolation.<init>(I)V
   * Goal 27. Percolation.isOpen(II)Z
   * Goal 28. Percolation.<init>(I)V
   * Goal 29. Percolation.isOpen(II)Z
   * Goal 30. Weak Mutation 0: Percolation.<init>(I)V:22 - InsertUnaryOp Negation
   * Goal 31. Weak Mutation 1: Percolation.<init>(I)V:22 - InsertUnaryOp IINC 1
   * Goal 32. Weak Mutation 2: Percolation.<init>(I)V:22 - InsertUnaryOp IINC -1
   * Goal 33. Weak Mutation 3: Percolation.<init>(I)V:22 - ReplaceComparisonOperator <= -> -1
   * Goal 34. Weak Mutation 6: Percolation.<init>(I)V:22 - InsertUnaryOp Negation
   * Goal 35. Weak Mutation 7: Percolation.<init>(I)V:22 - InsertUnaryOp IINC 1
   * Goal 36. Weak Mutation 8: Percolation.<init>(I)V:22 - InsertUnaryOp IINC -1
   * Goal 37. Weak Mutation 9: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> 0
   * Goal 38. Weak Mutation 10: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> 1
   * Goal 39. Weak Mutation 11: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> -1
   * Goal 40. Weak Mutation 12: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> 65534
   * Goal 41. Weak Mutation 13: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> 65536
   * Goal 42. Weak Mutation 15: Percolation.<init>(I)V:22 - ReplaceComparisonOperator < -> -2
   * Goal 43. Weak Mutation 18: Percolation.<init>(I)V:25 - InsertUnaryOp Negation
   * Goal 44. Weak Mutation 19: Percolation.<init>(I)V:25 - InsertUnaryOp IINC 1
   * Goal 45. Weak Mutation 20: Percolation.<init>(I)V:25 - InsertUnaryOp IINC -1
   * Goal 46. Weak Mutation 21: Percolation.<init>(I)V:26 - InsertUnaryOp Negation
   * Goal 47. Weak Mutation 22: Percolation.<init>(I)V:26 - InsertUnaryOp IINC 1
   * Goal 48. Weak Mutation 23: Percolation.<init>(I)V:26 - InsertUnaryOp IINC -1
   * Goal 49. Weak Mutation 24: Percolation.<init>(I)V:26 - InsertUnaryOp Negation
   * Goal 50. Weak Mutation 25: Percolation.<init>(I)V:26 - InsertUnaryOp IINC 1
   * Goal 51. Weak Mutation 26: Percolation.<init>(I)V:26 - InsertUnaryOp IINC -1
   * Goal 52. Weak Mutation 28: Percolation.<init>(I)V:26 - ReplaceArithmeticOperator * -> %
   * Goal 53. Weak Mutation 29: Percolation.<init>(I)V:26 - ReplaceArithmeticOperator * -> -
   * Goal 54. Weak Mutation 30: Percolation.<init>(I)V:26 - ReplaceArithmeticOperator * -> /
   * Goal 55. Weak Mutation 31: Percolation.<init>(I)V:28 - InsertUnaryOp Negation
   * Goal 56. Weak Mutation 32: Percolation.<init>(I)V:28 - InsertUnaryOp IINC 1
   * Goal 57. Weak Mutation 33: Percolation.<init>(I)V:28 - InsertUnaryOp IINC -1
   * Goal 58. Weak Mutation 34: Percolation.<init>(I)V:28 - InsertUnaryOp Negation
   * Goal 59. Weak Mutation 35: Percolation.<init>(I)V:28 - InsertUnaryOp IINC 1
   * Goal 60. Weak Mutation 36: Percolation.<init>(I)V:28 - InsertUnaryOp IINC -1
   * Goal 61. Weak Mutation 38: Percolation.<init>(I)V:28 - ReplaceArithmeticOperator * -> %
   * Goal 62. Weak Mutation 39: Percolation.<init>(I)V:28 - ReplaceArithmeticOperator * -> -
   * Goal 63. Weak Mutation 40: Percolation.<init>(I)V:28 - ReplaceArithmeticOperator * -> /
   * Goal 64. Weak Mutation 41: Percolation.<init>(I)V:29 - InsertUnaryOp Negation
   * Goal 65. Weak Mutation 42: Percolation.<init>(I)V:29 - InsertUnaryOp IINC 1
   * Goal 66. Weak Mutation 43: Percolation.<init>(I)V:29 - InsertUnaryOp IINC -1
   * Goal 67. Weak Mutation 44: Percolation.<init>(I)V:29 - InsertUnaryOp Negation
   * Goal 68. Weak Mutation 45: Percolation.<init>(I)V:29 - InsertUnaryOp IINC 1
   * Goal 69. Weak Mutation 46: Percolation.<init>(I)V:29 - InsertUnaryOp IINC -1
   * Goal 70. Weak Mutation 48: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator * -> %
   * Goal 71. Weak Mutation 49: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator * -> -
   * Goal 72. Weak Mutation 50: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator * -> /
   * Goal 73. Weak Mutation 51: Percolation.<init>(I)V:29 - ReplaceConstant - 1 -> 0
   * Goal 74. Weak Mutation 52: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator + -> %
   * Goal 75. Weak Mutation 53: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator + -> -
   * Goal 76. Weak Mutation 54: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator + -> *
   * Goal 77. Weak Mutation 55: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator + -> /
   * Goal 78. Weak Mutation 56: Percolation.<init>(I)V:30 - InsertUnaryOp Negation
   * Goal 79. Weak Mutation 57: Percolation.<init>(I)V:30 - InsertUnaryOp IINC 1
   * Goal 80. Weak Mutation 58: Percolation.<init>(I)V:30 - InsertUnaryOp IINC -1
   * Goal 81. Weak Mutation 59: Percolation.<init>(I)V:30 - InsertUnaryOp Negation
   * Goal 82. Weak Mutation 60: Percolation.<init>(I)V:30 - InsertUnaryOp IINC 1
   * Goal 83. Weak Mutation 61: Percolation.<init>(I)V:30 - InsertUnaryOp IINC -1
   * Goal 84. Weak Mutation 63: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator * -> %
   * Goal 85. Weak Mutation 64: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator * -> -
   * Goal 86. Weak Mutation 65: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator * -> /
   * Goal 87. Weak Mutation 66: Percolation.<init>(I)V:30 - ReplaceConstant - 2 -> 0
   * Goal 88. Weak Mutation 67: Percolation.<init>(I)V:30 - ReplaceConstant - 2 -> 1
   * Goal 89. Weak Mutation 68: Percolation.<init>(I)V:30 - ReplaceConstant - 2 -> -1
   * Goal 90. Weak Mutation 69: Percolation.<init>(I)V:30 - ReplaceConstant - 2 -> 3
   * Goal 91. Weak Mutation 70: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator + -> %
   * Goal 92. Weak Mutation 71: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator + -> -
   * Goal 93. Weak Mutation 72: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator + -> *
   * Goal 94. Weak Mutation 73: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator + -> /
   * Goal 95. Weak Mutation 74: Percolation.<init>(I)V:31 - InsertUnaryOp Negation
   * Goal 96. Weak Mutation 75: Percolation.<init>(I)V:31 - InsertUnaryOp IINC 1
   * Goal 97. Weak Mutation 76: Percolation.<init>(I)V:31 - InsertUnaryOp IINC -1
   * Goal 98. Weak Mutation 77: Percolation.<init>(I)V:31 - InsertUnaryOp Negation
   * Goal 99. Weak Mutation 78: Percolation.<init>(I)V:31 - InsertUnaryOp IINC 1
   * Goal 100. Weak Mutation 79: Percolation.<init>(I)V:31 - InsertUnaryOp IINC -1
   * Goal 101. Weak Mutation 81: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator * -> %
   * Goal 102. Weak Mutation 82: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator * -> -
   * Goal 103. Weak Mutation 83: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator * -> /
   * Goal 104. Weak Mutation 84: Percolation.<init>(I)V:31 - ReplaceConstant - 2 -> 0
   * Goal 105. Weak Mutation 85: Percolation.<init>(I)V:31 - ReplaceConstant - 2 -> 1
   * Goal 106. Weak Mutation 86: Percolation.<init>(I)V:31 - ReplaceConstant - 2 -> -1
   * Goal 107. Weak Mutation 87: Percolation.<init>(I)V:31 - ReplaceConstant - 2 -> 3
   * Goal 108. Weak Mutation 88: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator + -> %
   * Goal 109. Weak Mutation 89: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator + -> -
   * Goal 110. Weak Mutation 90: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator + -> *
   * Goal 111. Weak Mutation 91: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator + -> /
   * Goal 112. Weak Mutation 212: Percolation.isOpen(II)Z:79 - InsertUnaryOp Negation
   * Goal 113. Weak Mutation 213: Percolation.isOpen(II)Z:79 - InsertUnaryOp IINC 1
   * Goal 114. Weak Mutation 214: Percolation.isOpen(II)Z:79 - InsertUnaryOp IINC -1
   * Goal 115. Weak Mutation 215: Percolation.isOpen(II)Z:79 - InsertUnaryOp Negation
   * Goal 116. Weak Mutation 216: Percolation.isOpen(II)Z:79 - InsertUnaryOp IINC 1
   * Goal 117. Weak Mutation 217: Percolation.isOpen(II)Z:79 - InsertUnaryOp IINC -1
   * Goal 118. Weak Mutation 233: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 119. Weak Mutation 234: Percolation.index(II)I:94 - InsertUnaryOp IINC 1
   * Goal 120. Weak Mutation 235: Percolation.index(II)I:94 - InsertUnaryOp IINC -1
   * Goal 121. Weak Mutation 236: Percolation.index(II)I:94 - ReplaceComparisonOperator <= -> -1
   * Goal 122. Weak Mutation 239: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 123. Weak Mutation 240: Percolation.index(II)I:94 - InsertUnaryOp IINC 1
   * Goal 124. Weak Mutation 241: Percolation.index(II)I:94 - InsertUnaryOp IINC -1
   * Goal 125. Weak Mutation 242: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 126. Weak Mutation 243: Percolation.index(II)I:94 - InsertUnaryOp +1
   * Goal 127. Weak Mutation 244: Percolation.index(II)I:94 - InsertUnaryOp -1
   * Goal 128. Weak Mutation 247: Percolation.index(II)I:94 - ReplaceComparisonOperator > -> >=
   * Goal 129. Weak Mutation 248: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 130. Weak Mutation 249: Percolation.index(II)I:94 - InsertUnaryOp IINC 1
   * Goal 131. Weak Mutation 250: Percolation.index(II)I:94 - InsertUnaryOp IINC -1
   * Goal 132. Weak Mutation 251: Percolation.index(II)I:94 - ReplaceComparisonOperator <= -> -1
   * Goal 133. Weak Mutation 254: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 134. Weak Mutation 255: Percolation.index(II)I:94 - InsertUnaryOp IINC 1
   * Goal 135. Weak Mutation 256: Percolation.index(II)I:94 - InsertUnaryOp IINC -1
   * Goal 136. Weak Mutation 257: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 137. Weak Mutation 258: Percolation.index(II)I:94 - InsertUnaryOp +1
   * Goal 138. Weak Mutation 259: Percolation.index(II)I:94 - InsertUnaryOp -1
   * Goal 139. Weak Mutation 261: Percolation.index(II)I:94 - ReplaceComparisonOperator <= -> <
   * Goal 140. Weak Mutation 279: Percolation.index(II)I:97 - InsertUnaryOp Negation
   * Goal 141. Weak Mutation 280: Percolation.index(II)I:97 - InsertUnaryOp IINC 1
   * Goal 142. Weak Mutation 281: Percolation.index(II)I:97 - InsertUnaryOp IINC -1
   * Goal 143. Weak Mutation 282: Percolation.index(II)I:97 - ReplaceConstant - 1 -> 0
   * Goal 144. Weak Mutation 283: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> +
   * Goal 145. Weak Mutation 284: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> %
   * Goal 146. Weak Mutation 285: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> *
   * Goal 147. Weak Mutation 286: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> /
   * Goal 148. Weak Mutation 287: Percolation.index(II)I:97 - InsertUnaryOp Negation
   * Goal 149. Weak Mutation 288: Percolation.index(II)I:97 - InsertUnaryOp +1
   * Goal 150. Weak Mutation 289: Percolation.index(II)I:97 - InsertUnaryOp -1
   * Goal 151. Weak Mutation 290: Percolation.index(II)I:97 - ReplaceArithmeticOperator * -> +
   * Goal 152. Weak Mutation 291: Percolation.index(II)I:97 - ReplaceArithmeticOperator * -> %
   * Goal 153. Weak Mutation 292: Percolation.index(II)I:97 - ReplaceArithmeticOperator * -> -
   * Goal 154. Weak Mutation 293: Percolation.index(II)I:97 - ReplaceArithmeticOperator * -> /
   * Goal 155. Weak Mutation 294: Percolation.index(II)I:97 - InsertUnaryOp Negation
   * Goal 156. Weak Mutation 295: Percolation.index(II)I:97 - InsertUnaryOp IINC 1
   * Goal 157. Weak Mutation 296: Percolation.index(II)I:97 - InsertUnaryOp IINC -1
   * Goal 158. Weak Mutation 297: Percolation.index(II)I:97 - ReplaceConstant - 1 -> 0
   * Goal 159. Weak Mutation 298: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> +
   * Goal 160. Weak Mutation 299: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> %
   * Goal 161. Weak Mutation 300: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> *
   * Goal 162. Weak Mutation 301: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> /
   * Goal 163. Weak Mutation 302: Percolation.index(II)I:97 - ReplaceArithmeticOperator + -> %
   * Goal 164. Weak Mutation 303: Percolation.index(II)I:97 - ReplaceArithmeticOperator + -> -
   * Goal 165. Weak Mutation 304: Percolation.index(II)I:97 - ReplaceArithmeticOperator + -> *
   * Goal 166. Weak Mutation 305: Percolation.index(II)I:97 - ReplaceArithmeticOperator + -> /
   * Goal 167. Percolation.isOpen(II)Z:false
   */

  @Test
  public void test0()  throws Throwable  {
      int int0 = 2;
      Percolation percolation0 = new Percolation(2);
      boolean boolean0 = percolation0.isOpen(int0, int0);
      assertFalse(boolean0);
  }

  //Test case number: 1
  /*
   * 258 covered goals:
   * Goal 1. Percolation.isOpen(II)Z: root-Branch
   * Goal 2. Percolation.<init>(I)V: I7 Branch 1 IFLE L22 - false
   * Goal 3. Percolation.<init>(I)V: I10 Branch 2 IF_ICMPLT L22 - true
   * Goal 4. Percolation.open(II)V: I6 Branch 3 IFEQ L38 - true
   * Goal 5. Percolation.open(II)V: I28 Branch 4 IF_ICMPNE L44 - false
   * Goal 6. Percolation.open(II)V: I50 Branch 5 IF_ICMPNE L48 - true
   * Goal 7. Percolation.open(II)V: I63 Branch 6 IF_ICMPLE L53 - false
   * Goal 8. Percolation.open(II)V: I70 Branch 7 IFEQ L53 - true
   * Goal 9. Percolation.open(II)V: I99 Branch 8 IF_ICMPLE L59 - true
   * Goal 10. Percolation.open(II)V: I136 Branch 10 IF_ICMPGE L65 - true
   * Goal 11. Percolation.open(II)V: I173 Branch 12 IF_ICMPGE L71 - false
   * Goal 12. Percolation.open(II)V: I180 Branch 13 IFEQ L71 - true
   * Goal 13. Percolation.index(II)I: I3 Branch 14 IFLE L94 - false
   * Goal 14. Percolation.index(II)I: I7 Branch 15 IF_ICMPGT L94 - false
   * Goal 15. Percolation.index(II)I: I9 Branch 16 IFLE L94 - false
   * Goal 16. Percolation.index(II)I: I13 Branch 17 IF_ICMPLE L94 - true
   * Goal 17. Branch Percolation.<init>(I)V: I10 Branch 2 IF_ICMPLT L22 - true in context: Percolation:<init>(I)V
   * Goal 18. Branch Percolation.<init>(I)V: I7 Branch 1 IFLE L22 - false in context: Percolation:<init>(I)V
   * Goal 19. Branch Percolation.open(II)V: I6 Branch 3 IFEQ L38 - true in context: Percolation:open(II)V
   * Goal 20. Branch Percolation.open(II)V: I28 Branch 4 IF_ICMPNE L44 - false in context: Percolation:open(II)V
   * Goal 21. Branch Percolation.open(II)V: I50 Branch 5 IF_ICMPNE L48 - true in context: Percolation:open(II)V
   * Goal 22. Branch Percolation.open(II)V: I70 Branch 7 IFEQ L53 - true in context: Percolation:open(II)V
   * Goal 23. Branch Percolation.open(II)V: I63 Branch 6 IF_ICMPLE L53 - false in context: Percolation:open(II)V
   * Goal 24. Branch Percolation.open(II)V: I99 Branch 8 IF_ICMPLE L59 - true in context: Percolation:open(II)V
   * Goal 25. Branch Percolation.open(II)V: I136 Branch 10 IF_ICMPGE L65 - true in context: Percolation:open(II)V
   * Goal 26. Branch Percolation.open(II)V: I173 Branch 12 IF_ICMPGE L71 - false in context: Percolation:open(II)V
   * Goal 27. Branch Percolation.open(II)V: I180 Branch 13 IFEQ L71 - true in context: Percolation:open(II)V
   * Goal 28. Branch Percolation.index(II)I: I9 Branch 16 IFLE L94 - false in context: 
   * Goal 29. Branch Percolation.index(II)I: I3 Branch 14 IFLE L94 - false in context: 
   * Goal 30. Branch Percolation.index(II)I: I7 Branch 15 IF_ICMPGT L94 - false in context: 
   * Goal 31. Branch Percolation.index(II)I: I13 Branch 17 IF_ICMPLE L94 - true in context: 
   * Goal 32. Percolation.<init>(I)V: Line 22
   * Goal 33. Percolation.<init>(I)V: Line 25
   * Goal 34. Percolation.<init>(I)V: Line 26
   * Goal 35. Percolation.<init>(I)V: Line 28
   * Goal 36. Percolation.<init>(I)V: Line 29
   * Goal 37. Percolation.<init>(I)V: Line 30
   * Goal 38. Percolation.<init>(I)V: Line 31
   * Goal 39. Percolation.<init>(I)V: Line 32
   * Goal 40. Percolation.index(II)I: Line 94
   * Goal 41. Percolation.index(II)I: Line 97
   * Goal 42. Percolation.isOpen(II)Z: Line 79
   * Goal 43. Percolation.open(II)V: Line 38
   * Goal 44. Percolation.open(II)V: Line 40
   * Goal 45. Percolation.open(II)V: Line 41
   * Goal 46. Percolation.open(II)V: Line 44
   * Goal 47. Percolation.open(II)V: Line 45
   * Goal 48. Percolation.open(II)V: Line 46
   * Goal 49. Percolation.open(II)V: Line 48
   * Goal 50. Percolation.open(II)V: Line 53
   * Goal 51. Percolation.open(II)V: Line 59
   * Goal 52. Percolation.open(II)V: Line 65
   * Goal 53. Percolation.open(II)V: Line 71
   * Goal 54. Percolation.open(II)V: Line 75
   * Goal 55. Percolation.<init>(I)V
   * Goal 56. Percolation.open(II)V
   * Goal 57. Percolation.<init>(I)V
   * Goal 58. Percolation.open(II)V
   * Goal 59. Weak Mutation 0: Percolation.<init>(I)V:22 - InsertUnaryOp Negation
   * Goal 60. Weak Mutation 1: Percolation.<init>(I)V:22 - InsertUnaryOp IINC 1
   * Goal 61. Weak Mutation 2: Percolation.<init>(I)V:22 - InsertUnaryOp IINC -1
   * Goal 62. Weak Mutation 3: Percolation.<init>(I)V:22 - ReplaceComparisonOperator <= -> -1
   * Goal 63. Weak Mutation 6: Percolation.<init>(I)V:22 - InsertUnaryOp Negation
   * Goal 64. Weak Mutation 7: Percolation.<init>(I)V:22 - InsertUnaryOp IINC 1
   * Goal 65. Weak Mutation 8: Percolation.<init>(I)V:22 - InsertUnaryOp IINC -1
   * Goal 66. Weak Mutation 9: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> 0
   * Goal 67. Weak Mutation 10: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> 1
   * Goal 68. Weak Mutation 11: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> -1
   * Goal 69. Weak Mutation 12: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> 65534
   * Goal 70. Weak Mutation 13: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> 65536
   * Goal 71. Weak Mutation 15: Percolation.<init>(I)V:22 - ReplaceComparisonOperator < -> -2
   * Goal 72. Weak Mutation 18: Percolation.<init>(I)V:25 - InsertUnaryOp Negation
   * Goal 73. Weak Mutation 19: Percolation.<init>(I)V:25 - InsertUnaryOp IINC 1
   * Goal 74. Weak Mutation 20: Percolation.<init>(I)V:25 - InsertUnaryOp IINC -1
   * Goal 75. Weak Mutation 21: Percolation.<init>(I)V:26 - InsertUnaryOp Negation
   * Goal 76. Weak Mutation 22: Percolation.<init>(I)V:26 - InsertUnaryOp IINC 1
   * Goal 77. Weak Mutation 23: Percolation.<init>(I)V:26 - InsertUnaryOp IINC -1
   * Goal 78. Weak Mutation 24: Percolation.<init>(I)V:26 - InsertUnaryOp Negation
   * Goal 79. Weak Mutation 25: Percolation.<init>(I)V:26 - InsertUnaryOp IINC 1
   * Goal 80. Weak Mutation 26: Percolation.<init>(I)V:26 - InsertUnaryOp IINC -1
   * Goal 81. Weak Mutation 28: Percolation.<init>(I)V:26 - ReplaceArithmeticOperator * -> %
   * Goal 82. Weak Mutation 29: Percolation.<init>(I)V:26 - ReplaceArithmeticOperator * -> -
   * Goal 83. Weak Mutation 30: Percolation.<init>(I)V:26 - ReplaceArithmeticOperator * -> /
   * Goal 84. Weak Mutation 31: Percolation.<init>(I)V:28 - InsertUnaryOp Negation
   * Goal 85. Weak Mutation 32: Percolation.<init>(I)V:28 - InsertUnaryOp IINC 1
   * Goal 86. Weak Mutation 33: Percolation.<init>(I)V:28 - InsertUnaryOp IINC -1
   * Goal 87. Weak Mutation 34: Percolation.<init>(I)V:28 - InsertUnaryOp Negation
   * Goal 88. Weak Mutation 35: Percolation.<init>(I)V:28 - InsertUnaryOp IINC 1
   * Goal 89. Weak Mutation 36: Percolation.<init>(I)V:28 - InsertUnaryOp IINC -1
   * Goal 90. Weak Mutation 38: Percolation.<init>(I)V:28 - ReplaceArithmeticOperator * -> %
   * Goal 91. Weak Mutation 39: Percolation.<init>(I)V:28 - ReplaceArithmeticOperator * -> -
   * Goal 92. Weak Mutation 40: Percolation.<init>(I)V:28 - ReplaceArithmeticOperator * -> /
   * Goal 93. Weak Mutation 41: Percolation.<init>(I)V:29 - InsertUnaryOp Negation
   * Goal 94. Weak Mutation 42: Percolation.<init>(I)V:29 - InsertUnaryOp IINC 1
   * Goal 95. Weak Mutation 43: Percolation.<init>(I)V:29 - InsertUnaryOp IINC -1
   * Goal 96. Weak Mutation 44: Percolation.<init>(I)V:29 - InsertUnaryOp Negation
   * Goal 97. Weak Mutation 45: Percolation.<init>(I)V:29 - InsertUnaryOp IINC 1
   * Goal 98. Weak Mutation 46: Percolation.<init>(I)V:29 - InsertUnaryOp IINC -1
   * Goal 99. Weak Mutation 48: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator * -> %
   * Goal 100. Weak Mutation 49: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator * -> -
   * Goal 101. Weak Mutation 50: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator * -> /
   * Goal 102. Weak Mutation 51: Percolation.<init>(I)V:29 - ReplaceConstant - 1 -> 0
   * Goal 103. Weak Mutation 52: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator + -> %
   * Goal 104. Weak Mutation 53: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator + -> -
   * Goal 105. Weak Mutation 54: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator + -> *
   * Goal 106. Weak Mutation 55: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator + -> /
   * Goal 107. Weak Mutation 56: Percolation.<init>(I)V:30 - InsertUnaryOp Negation
   * Goal 108. Weak Mutation 57: Percolation.<init>(I)V:30 - InsertUnaryOp IINC 1
   * Goal 109. Weak Mutation 58: Percolation.<init>(I)V:30 - InsertUnaryOp IINC -1
   * Goal 110. Weak Mutation 59: Percolation.<init>(I)V:30 - InsertUnaryOp Negation
   * Goal 111. Weak Mutation 60: Percolation.<init>(I)V:30 - InsertUnaryOp IINC 1
   * Goal 112. Weak Mutation 61: Percolation.<init>(I)V:30 - InsertUnaryOp IINC -1
   * Goal 113. Weak Mutation 63: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator * -> %
   * Goal 114. Weak Mutation 64: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator * -> -
   * Goal 115. Weak Mutation 65: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator * -> /
   * Goal 116. Weak Mutation 66: Percolation.<init>(I)V:30 - ReplaceConstant - 2 -> 0
   * Goal 117. Weak Mutation 67: Percolation.<init>(I)V:30 - ReplaceConstant - 2 -> 1
   * Goal 118. Weak Mutation 68: Percolation.<init>(I)V:30 - ReplaceConstant - 2 -> -1
   * Goal 119. Weak Mutation 69: Percolation.<init>(I)V:30 - ReplaceConstant - 2 -> 3
   * Goal 120. Weak Mutation 70: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator + -> %
   * Goal 121. Weak Mutation 71: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator + -> -
   * Goal 122. Weak Mutation 72: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator + -> *
   * Goal 123. Weak Mutation 73: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator + -> /
   * Goal 124. Weak Mutation 74: Percolation.<init>(I)V:31 - InsertUnaryOp Negation
   * Goal 125. Weak Mutation 75: Percolation.<init>(I)V:31 - InsertUnaryOp IINC 1
   * Goal 126. Weak Mutation 76: Percolation.<init>(I)V:31 - InsertUnaryOp IINC -1
   * Goal 127. Weak Mutation 77: Percolation.<init>(I)V:31 - InsertUnaryOp Negation
   * Goal 128. Weak Mutation 78: Percolation.<init>(I)V:31 - InsertUnaryOp IINC 1
   * Goal 129. Weak Mutation 79: Percolation.<init>(I)V:31 - InsertUnaryOp IINC -1
   * Goal 130. Weak Mutation 81: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator * -> %
   * Goal 131. Weak Mutation 82: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator * -> -
   * Goal 132. Weak Mutation 83: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator * -> /
   * Goal 133. Weak Mutation 84: Percolation.<init>(I)V:31 - ReplaceConstant - 2 -> 0
   * Goal 134. Weak Mutation 85: Percolation.<init>(I)V:31 - ReplaceConstant - 2 -> 1
   * Goal 135. Weak Mutation 86: Percolation.<init>(I)V:31 - ReplaceConstant - 2 -> -1
   * Goal 136. Weak Mutation 87: Percolation.<init>(I)V:31 - ReplaceConstant - 2 -> 3
   * Goal 137. Weak Mutation 88: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator + -> %
   * Goal 138. Weak Mutation 89: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator + -> -
   * Goal 139. Weak Mutation 90: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator + -> *
   * Goal 140. Weak Mutation 91: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator + -> /
   * Goal 141. Weak Mutation 92: Percolation.open(II)V:38 - InsertUnaryOp Negation
   * Goal 142. Weak Mutation 93: Percolation.open(II)V:38 - InsertUnaryOp IINC 1
   * Goal 143. Weak Mutation 94: Percolation.open(II)V:38 - InsertUnaryOp IINC -1
   * Goal 144. Weak Mutation 95: Percolation.open(II)V:38 - InsertUnaryOp Negation
   * Goal 145. Weak Mutation 96: Percolation.open(II)V:38 - InsertUnaryOp IINC 1
   * Goal 146. Weak Mutation 97: Percolation.open(II)V:38 - InsertUnaryOp IINC -1
   * Goal 147. Weak Mutation 98: Percolation.open(II)V:38 - ReplaceComparisonOperator == -> !=
   * Goal 148. Weak Mutation 99: Percolation.open(II)V:40 - InsertUnaryOp Negation
   * Goal 149. Weak Mutation 100: Percolation.open(II)V:40 - InsertUnaryOp IINC 1
   * Goal 150. Weak Mutation 101: Percolation.open(II)V:40 - InsertUnaryOp IINC -1
   * Goal 151. Weak Mutation 102: Percolation.open(II)V:40 - InsertUnaryOp Negation
   * Goal 152. Weak Mutation 103: Percolation.open(II)V:40 - InsertUnaryOp IINC 1
   * Goal 153. Weak Mutation 104: Percolation.open(II)V:40 - InsertUnaryOp IINC -1
   * Goal 154. Weak Mutation 105: Percolation.open(II)V:41 - InsertUnaryOp Negation
   * Goal 155. Weak Mutation 106: Percolation.open(II)V:41 - ReplaceConstant - 1 -> 0
   * Goal 156. Weak Mutation 107: Percolation.open(II)V:44 - InsertUnaryOp Negation
   * Goal 157. Weak Mutation 108: Percolation.open(II)V:44 - InsertUnaryOp IINC 1
   * Goal 158. Weak Mutation 109: Percolation.open(II)V:44 - InsertUnaryOp IINC -1
   * Goal 159. Weak Mutation 110: Percolation.open(II)V:44 - ReplaceConstant - 1 -> 0
   * Goal 160. Weak Mutation 111: Percolation.open(II)V:44 - ReplaceComparisonOperator != -> ==
   * Goal 161. Weak Mutation 112: Percolation.open(II)V:45 - InsertUnaryOp Negation
   * Goal 162. Weak Mutation 113: Percolation.open(II)V:45 - InsertUnaryOp +1
   * Goal 163. Weak Mutation 114: Percolation.open(II)V:45 - InsertUnaryOp -1
   * Goal 164. Weak Mutation 115: Percolation.open(II)V:45 - InsertUnaryOp Negation
   * Goal 165. Weak Mutation 116: Percolation.open(II)V:45 - InsertUnaryOp IINC 1
   * Goal 166. Weak Mutation 117: Percolation.open(II)V:45 - InsertUnaryOp IINC -1
   * Goal 167. Weak Mutation 118: Percolation.open(II)V:46 - InsertUnaryOp Negation
   * Goal 168. Weak Mutation 119: Percolation.open(II)V:46 - InsertUnaryOp +1
   * Goal 169. Weak Mutation 120: Percolation.open(II)V:46 - InsertUnaryOp -1
   * Goal 170. Weak Mutation 121: Percolation.open(II)V:46 - InsertUnaryOp Negation
   * Goal 171. Weak Mutation 122: Percolation.open(II)V:46 - InsertUnaryOp IINC 1
   * Goal 172. Weak Mutation 123: Percolation.open(II)V:46 - InsertUnaryOp IINC -1
   * Goal 173. Weak Mutation 124: Percolation.open(II)V:48 - InsertUnaryOp Negation
   * Goal 174. Weak Mutation 125: Percolation.open(II)V:48 - InsertUnaryOp IINC 1
   * Goal 175. Weak Mutation 126: Percolation.open(II)V:48 - InsertUnaryOp IINC -1
   * Goal 176. Weak Mutation 127: Percolation.open(II)V:48 - InsertUnaryOp Negation
   * Goal 177. Weak Mutation 128: Percolation.open(II)V:48 - InsertUnaryOp +1
   * Goal 178. Weak Mutation 129: Percolation.open(II)V:48 - InsertUnaryOp -1
   * Goal 179. Weak Mutation 132: Percolation.open(II)V:48 - ReplaceComparisonOperator != -> >
   * Goal 180. Weak Mutation 139: Percolation.open(II)V:53 - InsertUnaryOp Negation
   * Goal 181. Weak Mutation 140: Percolation.open(II)V:53 - InsertUnaryOp IINC 1
   * Goal 182. Weak Mutation 141: Percolation.open(II)V:53 - InsertUnaryOp IINC -1
   * Goal 183. Weak Mutation 142: Percolation.open(II)V:53 - ReplaceConstant - 1 -> 0
   * Goal 184. Weak Mutation 143: Percolation.open(II)V:53 - ReplaceComparisonOperator <= -> >
   * Goal 185. Weak Mutation 144: Percolation.open(II)V:53 - InsertUnaryOp Negation
   * Goal 186. Weak Mutation 145: Percolation.open(II)V:53 - InsertUnaryOp IINC 1
   * Goal 187. Weak Mutation 146: Percolation.open(II)V:53 - InsertUnaryOp IINC -1
   * Goal 188. Weak Mutation 147: Percolation.open(II)V:53 - InsertUnaryOp Negation
   * Goal 189. Weak Mutation 148: Percolation.open(II)V:53 - InsertUnaryOp IINC 1
   * Goal 190. Weak Mutation 149: Percolation.open(II)V:53 - InsertUnaryOp IINC -1
   * Goal 191. Weak Mutation 150: Percolation.open(II)V:53 - ReplaceConstant - 1 -> 0
   * Goal 192. Weak Mutation 151: Percolation.open(II)V:53 - ReplaceArithmeticOperator - -> +
   * Goal 193. Weak Mutation 152: Percolation.open(II)V:53 - ReplaceArithmeticOperator - -> %
   * Goal 194. Weak Mutation 153: Percolation.open(II)V:53 - ReplaceArithmeticOperator - -> *
   * Goal 195. Weak Mutation 154: Percolation.open(II)V:53 - ReplaceArithmeticOperator - -> /
   * Goal 196. Weak Mutation 155: Percolation.open(II)V:53 - ReplaceComparisonOperator == -> !=
   * Goal 197. Weak Mutation 184: Percolation.open(II)V:59 - InsertUnaryOp Negation
   * Goal 198. Weak Mutation 185: Percolation.open(II)V:59 - InsertUnaryOp IINC 1
   * Goal 199. Weak Mutation 186: Percolation.open(II)V:59 - InsertUnaryOp IINC -1
   * Goal 200. Weak Mutation 187: Percolation.open(II)V:59 - ReplaceConstant - 1 -> 0
   * Goal 201. Weak Mutation 188: Percolation.open(II)V:59 - ReplaceComparisonOperator <= -> >
   * Goal 202. Weak Mutation 212: Percolation.isOpen(II)Z:79 - InsertUnaryOp Negation
   * Goal 203. Weak Mutation 213: Percolation.isOpen(II)Z:79 - InsertUnaryOp IINC 1
   * Goal 204. Weak Mutation 214: Percolation.isOpen(II)Z:79 - InsertUnaryOp IINC -1
   * Goal 205. Weak Mutation 215: Percolation.isOpen(II)Z:79 - InsertUnaryOp Negation
   * Goal 206. Weak Mutation 216: Percolation.isOpen(II)Z:79 - InsertUnaryOp IINC 1
   * Goal 207. Weak Mutation 217: Percolation.isOpen(II)Z:79 - InsertUnaryOp IINC -1
   * Goal 208. Weak Mutation 233: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 209. Weak Mutation 234: Percolation.index(II)I:94 - InsertUnaryOp IINC 1
   * Goal 210. Weak Mutation 235: Percolation.index(II)I:94 - InsertUnaryOp IINC -1
   * Goal 211. Weak Mutation 236: Percolation.index(II)I:94 - ReplaceComparisonOperator <= -> -1
   * Goal 212. Weak Mutation 239: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 213. Weak Mutation 240: Percolation.index(II)I:94 - InsertUnaryOp IINC 1
   * Goal 214. Weak Mutation 241: Percolation.index(II)I:94 - InsertUnaryOp IINC -1
   * Goal 215. Weak Mutation 242: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 216. Weak Mutation 243: Percolation.index(II)I:94 - InsertUnaryOp +1
   * Goal 217. Weak Mutation 244: Percolation.index(II)I:94 - InsertUnaryOp -1
   * Goal 218. Weak Mutation 245: Percolation.index(II)I:94 - ReplaceComparisonOperator > -> !=
   * Goal 219. Weak Mutation 247: Percolation.index(II)I:94 - ReplaceComparisonOperator > -> >=
   * Goal 220. Weak Mutation 248: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 221. Weak Mutation 249: Percolation.index(II)I:94 - InsertUnaryOp IINC 1
   * Goal 222. Weak Mutation 250: Percolation.index(II)I:94 - InsertUnaryOp IINC -1
   * Goal 223. Weak Mutation 251: Percolation.index(II)I:94 - ReplaceComparisonOperator <= -> -1
   * Goal 224. Weak Mutation 254: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 225. Weak Mutation 255: Percolation.index(II)I:94 - InsertUnaryOp IINC 1
   * Goal 226. Weak Mutation 256: Percolation.index(II)I:94 - InsertUnaryOp IINC -1
   * Goal 227. Weak Mutation 257: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 228. Weak Mutation 258: Percolation.index(II)I:94 - InsertUnaryOp +1
   * Goal 229. Weak Mutation 259: Percolation.index(II)I:94 - InsertUnaryOp -1
   * Goal 230. Weak Mutation 261: Percolation.index(II)I:94 - ReplaceComparisonOperator <= -> <
   * Goal 231. Weak Mutation 262: Percolation.index(II)I:94 - ReplaceComparisonOperator <= -> ==
   * Goal 232. Weak Mutation 279: Percolation.index(II)I:97 - InsertUnaryOp Negation
   * Goal 233. Weak Mutation 280: Percolation.index(II)I:97 - InsertUnaryOp IINC 1
   * Goal 234. Weak Mutation 281: Percolation.index(II)I:97 - InsertUnaryOp IINC -1
   * Goal 235. Weak Mutation 282: Percolation.index(II)I:97 - ReplaceConstant - 1 -> 0
   * Goal 236. Weak Mutation 283: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> +
   * Goal 237. Weak Mutation 284: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> %
   * Goal 238. Weak Mutation 285: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> *
   * Goal 239. Weak Mutation 286: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> /
   * Goal 240. Weak Mutation 287: Percolation.index(II)I:97 - InsertUnaryOp Negation
   * Goal 241. Weak Mutation 288: Percolation.index(II)I:97 - InsertUnaryOp +1
   * Goal 242. Weak Mutation 289: Percolation.index(II)I:97 - InsertUnaryOp -1
   * Goal 243. Weak Mutation 290: Percolation.index(II)I:97 - ReplaceArithmeticOperator * -> +
   * Goal 244. Weak Mutation 291: Percolation.index(II)I:97 - ReplaceArithmeticOperator * -> %
   * Goal 245. Weak Mutation 292: Percolation.index(II)I:97 - ReplaceArithmeticOperator * -> -
   * Goal 246. Weak Mutation 293: Percolation.index(II)I:97 - ReplaceArithmeticOperator * -> /
   * Goal 247. Weak Mutation 294: Percolation.index(II)I:97 - InsertUnaryOp Negation
   * Goal 248. Weak Mutation 295: Percolation.index(II)I:97 - InsertUnaryOp IINC 1
   * Goal 249. Weak Mutation 296: Percolation.index(II)I:97 - InsertUnaryOp IINC -1
   * Goal 250. Weak Mutation 297: Percolation.index(II)I:97 - ReplaceConstant - 1 -> 0
   * Goal 251. Weak Mutation 298: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> +
   * Goal 252. Weak Mutation 299: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> %
   * Goal 253. Weak Mutation 300: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> *
   * Goal 254. Weak Mutation 301: Percolation.index(II)I:97 - ReplaceArithmeticOperator - -> /
   * Goal 255. Weak Mutation 302: Percolation.index(II)I:97 - ReplaceArithmeticOperator + -> %
   * Goal 256. Weak Mutation 303: Percolation.index(II)I:97 - ReplaceArithmeticOperator + -> -
   * Goal 257. Weak Mutation 304: Percolation.index(II)I:97 - ReplaceArithmeticOperator + -> *
   * Goal 258. Weak Mutation 305: Percolation.index(II)I:97 - ReplaceArithmeticOperator + -> /
   */

  @Test
  public void test1()  throws Throwable  {
      Percolation percolation0 = new Percolation(2);
      percolation0.open(1, 2);
  }

  //Test case number: 2
  /*
   * 134 covered goals:
   * Goal 1. Percolation.isFull(II)Z: root-Branch
   * Goal 2. Percolation.<init>(I)V: I7 Branch 1 IFLE L22 - false
   * Goal 3. Percolation.<init>(I)V: I10 Branch 2 IF_ICMPLT L22 - true
   * Goal 4. Percolation.index(II)I: I3 Branch 14 IFLE L94 - true
   * Goal 5. Branch Percolation.isFull(II)Z: root-Branch in context: Percolation:isFull(II)Z
   * Goal 6. Branch Percolation.<init>(I)V: I10 Branch 2 IF_ICMPLT L22 - true in context: Percolation:<init>(I)V
   * Goal 7. Branch Percolation.<init>(I)V: I7 Branch 1 IFLE L22 - false in context: Percolation:<init>(I)V
   * Goal 8. Branch Percolation.index(II)I: I3 Branch 14 IFLE L94 - true in context: 
   * Goal 9. isFull(II)Z_java.lang.IndexOutOfBoundsException_EXPLICIT
   * Goal 10. Percolation.<init>(I)V: Line 22
   * Goal 11. Percolation.<init>(I)V: Line 25
   * Goal 12. Percolation.<init>(I)V: Line 26
   * Goal 13. Percolation.<init>(I)V: Line 28
   * Goal 14. Percolation.<init>(I)V: Line 29
   * Goal 15. Percolation.<init>(I)V: Line 30
   * Goal 16. Percolation.<init>(I)V: Line 31
   * Goal 17. Percolation.<init>(I)V: Line 32
   * Goal 18. Percolation.index(II)I: Line 94
   * Goal 19. Percolation.index(II)I: Line 95
   * Goal 20. Percolation.isFull(II)Z: Line 84
   * Goal 21. Percolation.<init>(I)V
   * Goal 22. Percolation.isFull(II)Z
   * Goal 23. Percolation.<init>(I)V
   * Goal 24. Weak Mutation 0: Percolation.<init>(I)V:22 - InsertUnaryOp Negation
   * Goal 25. Weak Mutation 1: Percolation.<init>(I)V:22 - InsertUnaryOp IINC 1
   * Goal 26. Weak Mutation 2: Percolation.<init>(I)V:22 - InsertUnaryOp IINC -1
   * Goal 27. Weak Mutation 3: Percolation.<init>(I)V:22 - ReplaceComparisonOperator <= -> -1
   * Goal 28. Weak Mutation 6: Percolation.<init>(I)V:22 - InsertUnaryOp Negation
   * Goal 29. Weak Mutation 7: Percolation.<init>(I)V:22 - InsertUnaryOp IINC 1
   * Goal 30. Weak Mutation 8: Percolation.<init>(I)V:22 - InsertUnaryOp IINC -1
   * Goal 31. Weak Mutation 9: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> 0
   * Goal 32. Weak Mutation 10: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> 1
   * Goal 33. Weak Mutation 11: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> -1
   * Goal 34. Weak Mutation 12: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> 65534
   * Goal 35. Weak Mutation 13: Percolation.<init>(I)V:22 - ReplaceConstant - 65535 -> 65536
   * Goal 36. Weak Mutation 15: Percolation.<init>(I)V:22 - ReplaceComparisonOperator < -> -2
   * Goal 37. Weak Mutation 18: Percolation.<init>(I)V:25 - InsertUnaryOp Negation
   * Goal 38. Weak Mutation 19: Percolation.<init>(I)V:25 - InsertUnaryOp IINC 1
   * Goal 39. Weak Mutation 20: Percolation.<init>(I)V:25 - InsertUnaryOp IINC -1
   * Goal 40. Weak Mutation 21: Percolation.<init>(I)V:26 - InsertUnaryOp Negation
   * Goal 41. Weak Mutation 22: Percolation.<init>(I)V:26 - InsertUnaryOp IINC 1
   * Goal 42. Weak Mutation 23: Percolation.<init>(I)V:26 - InsertUnaryOp IINC -1
   * Goal 43. Weak Mutation 24: Percolation.<init>(I)V:26 - InsertUnaryOp Negation
   * Goal 44. Weak Mutation 25: Percolation.<init>(I)V:26 - InsertUnaryOp IINC 1
   * Goal 45. Weak Mutation 26: Percolation.<init>(I)V:26 - InsertUnaryOp IINC -1
   * Goal 46. Weak Mutation 28: Percolation.<init>(I)V:26 - ReplaceArithmeticOperator * -> %
   * Goal 47. Weak Mutation 29: Percolation.<init>(I)V:26 - ReplaceArithmeticOperator * -> -
   * Goal 48. Weak Mutation 30: Percolation.<init>(I)V:26 - ReplaceArithmeticOperator * -> /
   * Goal 49. Weak Mutation 31: Percolation.<init>(I)V:28 - InsertUnaryOp Negation
   * Goal 50. Weak Mutation 32: Percolation.<init>(I)V:28 - InsertUnaryOp IINC 1
   * Goal 51. Weak Mutation 33: Percolation.<init>(I)V:28 - InsertUnaryOp IINC -1
   * Goal 52. Weak Mutation 34: Percolation.<init>(I)V:28 - InsertUnaryOp Negation
   * Goal 53. Weak Mutation 35: Percolation.<init>(I)V:28 - InsertUnaryOp IINC 1
   * Goal 54. Weak Mutation 36: Percolation.<init>(I)V:28 - InsertUnaryOp IINC -1
   * Goal 55. Weak Mutation 38: Percolation.<init>(I)V:28 - ReplaceArithmeticOperator * -> %
   * Goal 56. Weak Mutation 39: Percolation.<init>(I)V:28 - ReplaceArithmeticOperator * -> -
   * Goal 57. Weak Mutation 40: Percolation.<init>(I)V:28 - ReplaceArithmeticOperator * -> /
   * Goal 58. Weak Mutation 41: Percolation.<init>(I)V:29 - InsertUnaryOp Negation
   * Goal 59. Weak Mutation 42: Percolation.<init>(I)V:29 - InsertUnaryOp IINC 1
   * Goal 60. Weak Mutation 43: Percolation.<init>(I)V:29 - InsertUnaryOp IINC -1
   * Goal 61. Weak Mutation 44: Percolation.<init>(I)V:29 - InsertUnaryOp Negation
   * Goal 62. Weak Mutation 45: Percolation.<init>(I)V:29 - InsertUnaryOp IINC 1
   * Goal 63. Weak Mutation 46: Percolation.<init>(I)V:29 - InsertUnaryOp IINC -1
   * Goal 64. Weak Mutation 48: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator * -> %
   * Goal 65. Weak Mutation 49: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator * -> -
   * Goal 66. Weak Mutation 50: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator * -> /
   * Goal 67. Weak Mutation 51: Percolation.<init>(I)V:29 - ReplaceConstant - 1 -> 0
   * Goal 68. Weak Mutation 52: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator + -> %
   * Goal 69. Weak Mutation 53: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator + -> -
   * Goal 70. Weak Mutation 54: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator + -> *
   * Goal 71. Weak Mutation 55: Percolation.<init>(I)V:29 - ReplaceArithmeticOperator + -> /
   * Goal 72. Weak Mutation 56: Percolation.<init>(I)V:30 - InsertUnaryOp Negation
   * Goal 73. Weak Mutation 57: Percolation.<init>(I)V:30 - InsertUnaryOp IINC 1
   * Goal 74. Weak Mutation 58: Percolation.<init>(I)V:30 - InsertUnaryOp IINC -1
   * Goal 75. Weak Mutation 59: Percolation.<init>(I)V:30 - InsertUnaryOp Negation
   * Goal 76. Weak Mutation 60: Percolation.<init>(I)V:30 - InsertUnaryOp IINC 1
   * Goal 77. Weak Mutation 61: Percolation.<init>(I)V:30 - InsertUnaryOp IINC -1
   * Goal 78. Weak Mutation 63: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator * -> %
   * Goal 79. Weak Mutation 64: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator * -> -
   * Goal 80. Weak Mutation 65: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator * -> /
   * Goal 81. Weak Mutation 66: Percolation.<init>(I)V:30 - ReplaceConstant - 2 -> 0
   * Goal 82. Weak Mutation 67: Percolation.<init>(I)V:30 - ReplaceConstant - 2 -> 1
   * Goal 83. Weak Mutation 68: Percolation.<init>(I)V:30 - ReplaceConstant - 2 -> -1
   * Goal 84. Weak Mutation 69: Percolation.<init>(I)V:30 - ReplaceConstant - 2 -> 3
   * Goal 85. Weak Mutation 70: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator + -> %
   * Goal 86. Weak Mutation 71: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator + -> -
   * Goal 87. Weak Mutation 72: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator + -> *
   * Goal 88. Weak Mutation 73: Percolation.<init>(I)V:30 - ReplaceArithmeticOperator + -> /
   * Goal 89. Weak Mutation 74: Percolation.<init>(I)V:31 - InsertUnaryOp Negation
   * Goal 90. Weak Mutation 75: Percolation.<init>(I)V:31 - InsertUnaryOp IINC 1
   * Goal 91. Weak Mutation 76: Percolation.<init>(I)V:31 - InsertUnaryOp IINC -1
   * Goal 92. Weak Mutation 77: Percolation.<init>(I)V:31 - InsertUnaryOp Negation
   * Goal 93. Weak Mutation 78: Percolation.<init>(I)V:31 - InsertUnaryOp IINC 1
   * Goal 94. Weak Mutation 79: Percolation.<init>(I)V:31 - InsertUnaryOp IINC -1
   * Goal 95. Weak Mutation 81: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator * -> %
   * Goal 96. Weak Mutation 82: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator * -> -
   * Goal 97. Weak Mutation 83: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator * -> /
   * Goal 98. Weak Mutation 84: Percolation.<init>(I)V:31 - ReplaceConstant - 2 -> 0
   * Goal 99. Weak Mutation 85: Percolation.<init>(I)V:31 - ReplaceConstant - 2 -> 1
   * Goal 100. Weak Mutation 86: Percolation.<init>(I)V:31 - ReplaceConstant - 2 -> -1
   * Goal 101. Weak Mutation 87: Percolation.<init>(I)V:31 - ReplaceConstant - 2 -> 3
   * Goal 102. Weak Mutation 88: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator + -> %
   * Goal 103. Weak Mutation 89: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator + -> -
   * Goal 104. Weak Mutation 90: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator + -> *
   * Goal 105. Weak Mutation 91: Percolation.<init>(I)V:31 - ReplaceArithmeticOperator + -> /
   * Goal 106. Weak Mutation 218: Percolation.isFull(II)Z:84 - InsertUnaryOp Negation
   * Goal 107. Weak Mutation 219: Percolation.isFull(II)Z:84 - InsertUnaryOp +1
   * Goal 108. Weak Mutation 220: Percolation.isFull(II)Z:84 - InsertUnaryOp -1
   * Goal 109. Weak Mutation 221: Percolation.isFull(II)Z:84 - InsertUnaryOp Negation
   * Goal 110. Weak Mutation 222: Percolation.isFull(II)Z:84 - InsertUnaryOp IINC 1
   * Goal 111. Weak Mutation 223: Percolation.isFull(II)Z:84 - InsertUnaryOp IINC -1
   * Goal 112. Weak Mutation 224: Percolation.isFull(II)Z:84 - InsertUnaryOp Negation
   * Goal 113. Weak Mutation 225: Percolation.isFull(II)Z:84 - InsertUnaryOp IINC 1
   * Goal 114. Weak Mutation 226: Percolation.isFull(II)Z:84 - InsertUnaryOp IINC -1
   * Goal 115. Weak Mutation 233: Percolation.index(II)I:94 - InsertUnaryOp Negation
   * Goal 116. Weak Mutation 234: Percolation.index(II)I:94 - InsertUnaryOp IINC 1
   * Goal 117. Weak Mutation 235: Percolation.index(II)I:94 - InsertUnaryOp IINC -1
   * Goal 118. Weak Mutation 238: Percolation.index(II)I:94 - ReplaceComparisonOperator <= -> <
   * Goal 119. Weak Mutation 263: Percolation.index(II)I:95 - InsertUnaryOp Negation
   * Goal 120. Weak Mutation 264: Percolation.index(II)I:95 - InsertUnaryOp IINC 1
   * Goal 121. Weak Mutation 265: Percolation.index(II)I:95 - InsertUnaryOp IINC -1
   * Goal 122. Weak Mutation 266: Percolation.index(II)I:95 - ReplaceConstant - , -> 
   * Goal 123. Weak Mutation 267: Percolation.index(II)I:95 - InsertUnaryOp Negation
   * Goal 124. Weak Mutation 268: Percolation.index(II)I:95 - InsertUnaryOp IINC 1
   * Goal 125. Weak Mutation 269: Percolation.index(II)I:95 - InsertUnaryOp IINC -1
   * Goal 126. Weak Mutation 270: Percolation.index(II)I:95 - ReplaceConstant -  is out of bounds -> 
   * Goal 127. Weak Mutation 271: Percolation.index(II)I:95 - ReplaceConstant -  for grid of  -> 
   * Goal 128. Weak Mutation 272: Percolation.index(II)I:95 - InsertUnaryOp Negation
   * Goal 129. Weak Mutation 273: Percolation.index(II)I:95 - InsertUnaryOp +1
   * Goal 130. Weak Mutation 274: Percolation.index(II)I:95 - InsertUnaryOp -1
   * Goal 131. Weak Mutation 275: Percolation.index(II)I:95 - ReplaceConstant -  x  -> 
   * Goal 132. Weak Mutation 276: Percolation.index(II)I:95 - InsertUnaryOp Negation
   * Goal 133. Weak Mutation 277: Percolation.index(II)I:95 - InsertUnaryOp +1
   * Goal 134. Weak Mutation 278: Percolation.index(II)I:95 - InsertUnaryOp -1
   */

  @Test
  public void test2()  throws Throwable  {
      Percolation percolation0 = new Percolation(2);
      // Undeclared exception!
      try { 
        percolation0.isFull(0, (-2091));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // 0,-2091 is out of bounds for grid of 2 x 2
         //
         assertThrownBy("Percolation", e);
      }
  }
}
